export type StatusTone = "success" | "warning" | "danger" | "info" | "neutral" | "ai";

export const clients = ["Atlas Packaging","AgroMaroc","Seafood Export","GreenFarm","Pack Solutions","Maroc Fresh","Casa Food Industries","Souss Agrumes","Oceanic Export","BioTerra","Nord Emballage","Fès Conserves","Marrakech Délices","Tanger Logistics","Rif Agro","Dakhla Seafood","Meknès Fruits","Oriental Pack","Sahara Foods","Kenitra Dairy"].map((name,i)=>({id:`CL-${String(i+1).padStart(3,"0")}`,name,contact:["Yassine Amrani","Salma Idrissi","Mehdi Alaoui","Nadia Benjelloun"][i%4],email:`contact@${name.toLowerCase().replaceAll(" ","")}.ma`,phone:`+212 6 ${41+i} 28 ${30+i} ${10+i}`,status:i%7===0?"À relancer":"Actif",orders:3+(i%12),revenue:18000+i*4150}));

export const conversations = Array.from({length:30},(_,i)=>({id:i+1,client:clients[i%clients.length].name,company:clients[i%clients.length].name,message:["Bonjour, quel est le délai pour 5 000 sacs personnalisés ?","Pouvez-vous me transmettre le devis actualisé ?","La commande sera-t-elle livrée cette semaine ?","Nous souhaitons modifier les dimensions du sachet."][i%4],time:`${String(9+(i%9)).padStart(2,"0")}:${i%2?"15":"40"}`,unread:i%4===0?2:0,status:i%5===0?"Résolue":i%3===0?"En attente":"En cours",priority:i%7===0?"Haute":"Normale"}));

export const orders = Array.from({length:30},(_,i)=>({id:`CMD-2026-${String(i+21).padStart(3,"0")}`,client:clients[i%clients.length].name,product:["Sachet PE transparent","Sac personnalisé","Film étirable","Housse industrielle","Gaine PE"][(i+1)%5],qty:2500+(i%8)*1500,amount:8200+i*970,date:`${String(2+(i%25)).padStart(2,"0")}/09/2026`,delivery:`${String(5+(i%23)).padStart(2,"0")}/10/2026`,status:["Nouvelle","À valider","Confirmée","En production","Expédiée","Livrée"][i%6],source:i%3===0?"WhatsApp":"Commercial"}));

export const quotes = Array.from({length:25},(_,i)=>({id:`DEV-2026-${String(i+1).padStart(3,"0")}`,client:clients[i%clients.length].name,product:["Sachet PE","Film PEBD","Sac imprimé","Gaine plastique"][i%4],qty:5000+(i%6)*2500,unitPrice:1.72+(i%5)*.09,total:10900+i*1240,date:`${String(1+(i%25)).padStart(2,"0")}/09/2026`,status:["Brouillon","En attente","Validé","Envoyé"][i%4],source:i%2?"Email":"WhatsApp"}));

export const materials = ["Film PE basse densité","Granulé PEHD naturel","Granulé PEBD recyclé","Masterbatch blanc","Masterbatch bleu","Additif anti-UV","Encre flexographique","Solvant industriel","Mandrin carton","Film BOPP","Granulé PP","Colle lamination","Pigment vert","Résine EVA","Agent glissant"].map((name,i)=>({ref:`MP-${String(i+1).padStart(3,"0")}`,name,category:i<10?"Matière première":"Consommable",current:[450,2400,0,780,320,95,640,180,1200,870,1560,210,430,510,75][i],min:[500,800,400,300,250,120,200,150,500,400,700,180,200,250,100][i],max:3000,unit:i===5||i===14?"L":"kg",updated:"Aujourd’hui, 14:32"}));

export const suppliers = ["Plastique Maroc","Polymeris Afrique","Casaplast Trading","Maghreb Polymères","Resinex Maroc","Atlas Chimie","Tanger Polymers","Souss Matières","ColorTech Maroc","PackSource","Industrie Résines","Maroc Additifs"].map((name,i)=>({id:`FR-${i+1}`,name,material:materials[i%materials.length].name,price:11.2+(i%4)*.3,delay:2+(i%6),reliability:88+(i%11),last:`${String(2+i).padStart(2,"0")}/08/2026`,status:i===0?"Sous surveillance":"Actif"}));

export const alerts = Array.from({length:15},(_,i)=>({id:i+1,title:i===0?"Stock critique : Film PE basse densité":i===1?"Retard fournisseur : Plastique Maroc":i===2?"5 demandes clients sans réponse":i===3?"3 devis nécessitent une validation":`Seuil de vigilance — ${materials[i%materials.length].name}`,module:i<2?"Stock & Achats":i<4?"Commercial":"Stock",priority:i%4===0?"Critique":i%3===0?"Haute":"Moyenne",date:`Aujourd’hui, ${9+i}:20`,handled:false}));

export const activities = ["Devis DEV-2026-018 validé","Commande CMD-2026-041 créée","Agent Service Client a répondu à AgroMaroc","Alerte stock Film PEBD déclenchée","BDC-2026-012 généré","Plastique Maroc sélectionné","DEV-2026-017 envoyé par email","Commande CMD-2026-038 expédiée","Document Catalogue produits indexé","Conversation Atlas Packaging escaladée","Seuil Masterbatch modifié","Nouveau client BioTerra créé","Paiement CMD-2026-036 confirmé","Scénario d’achat validé","Rapport mensuel exporté"].map((action,i)=>({date:`22/09/2026 · ${String(16-Math.floor(i/2)).padStart(2,"0")}:${i%2?"15":"42"}`,actor:i%3===0?"Admin":i%3===1?"Agent IA":"Système",action,module:["Devis","Commandes","Service Client","Stock","Achats"][i%5],object:action.match(/[A-Z]{3}-2026-\d+/)?.[0]||"—",status:"Succès"}));

export const documents = ["Catalogue produits.pdf","Fiches techniques.pdf","Conditions commerciales.pdf","Procédure SAV.pdf","Politique livraison.pdf","Conditions fournisseurs.pdf",...Array.from({length:14},(_,i)=>`Fiche matière ${String(i+1).padStart(2,"0")}.pdf`)].map((name,i)=>({id:i+1,name,type:"PDF",size:`${(1.2+i*.17).toFixed(1)} Mo`,date:`${String(2+(i%20)).padStart(2,"0")}/09/2026`,category:["Produits","Technique","Commercial","SAV","Logistique","Achats"][i%6],indexed:i%7!==0}));

export const faqs = Array.from({length:20},(_,i)=>({id:i+1,question:["Quels sont les délais de production ?","Quelle quantité minimale commander ?","Proposez-vous l’impression personnalisée ?","Comment suivre une commande ?","Quels moyens de paiement acceptez-vous ?"][i%5],answer:["Le délai standard varie de 5 à 10 jours ouvrables selon le produit.","La quantité minimale est généralement de 2 500 unités.","Oui, jusqu’à 6 couleurs selon le support.","Votre commercial partage le suivi à chaque étape.","Virement bancaire et règlement selon conditions contractuelles."][i%5],category:["Production","Commande","Personnalisation","Livraison","Paiement"][i%5],active:i%6!==0,updated:`${String(2+i%20).padStart(2,"0")}/09/2026`}));

export const chartData = [
 {m:"Avr",commandes:54,ca:680,stock:89,demandes:106},{m:"Mai",commandes:62,ca:735,stock:82,demandes:118},{m:"Juin",commandes:58,ca:710,stock:76,demandes:130},{m:"Juil",commandes:71,ca:840,stock:72,demandes:142},{m:"Août",commandes:68,ca:805,stock:69,demandes:136},{m:"Sep",commandes:86,ca:960,stock:74,demandes:168},
];
