import { Link, useRouterState, useNavigate } from "@tanstack/react-router";
import { useMemo, useState, type ReactNode } from "react";
import { LayoutDashboard, Headphones, FileText, Boxes, Truck, ChartNoAxesCombined, Settings2, Bell, History, SlidersHorizontal, Search, Menu, PanelLeftClose, PanelLeftOpen, Sparkles, LogOut, X, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { clients, orders, quotes, suppliers, materials, documents, conversations } from "@/lib/mock-data";

const nav = [
  ["/dashboard","Dashboard",LayoutDashboard],["/service-client","Service Client",Headphones],["/devis-commandes","Devis & Commandes",FileText],["/stock","Stock & Matières",Boxes],["/achats","Fournisseurs & Achats",Truck],["/analytics","Analytics & Reporting",ChartNoAxesCombined],["/configuration","Configuration",Settings2],["/notifications","Notifications",Bell],["/activite","Activité",History],["/parametres","Paramètres",SlidersHorizontal],
] as const;

export function AppShell({children,title,subtitle}:{children:ReactNode;title:string;subtitle?:string}) {
 const path=useRouterState({select:s=>s.location.pathname}); const navigate=useNavigate();
 const [collapsed,setCollapsed]=useState(false); const [mobile,setMobile]=useState(false); const [searchOpen,setSearchOpen]=useState(false); const [query,setQuery]=useState("");
 const results=useMemo(()=>{ if(query.length<2)return []; const q=query.toLowerCase(); return [
  ...clients.filter(x=>x.name.toLowerCase().includes(q)).slice(0,4).map(x=>({type:"Clients",label:x.name,detail:x.contact,to:"/service-client"})),
  ...orders.filter(x=>x.id.toLowerCase().includes(q)||x.client.toLowerCase().includes(q)).slice(0,4).map(x=>({type:"Commandes",label:x.id,detail:x.client,to:"/devis-commandes"})),
  ...quotes.filter(x=>x.id.toLowerCase().includes(q)||x.client.toLowerCase().includes(q)).slice(0,4).map(x=>({type:"Devis",label:x.id,detail:x.client,to:"/devis-commandes"})),
  ...suppliers.filter(x=>x.name.toLowerCase().includes(q)).slice(0,3).map(x=>({type:"Fournisseurs",label:x.name,detail:x.material,to:"/achats"})),
  ...materials.filter(x=>x.name.toLowerCase().includes(q)).slice(0,3).map(x=>({type:"Matières",label:x.name,detail:x.ref,to:"/stock"})),
  ...documents.filter(x=>x.name.toLowerCase().includes(q)).slice(0,3).map(x=>({type:"Documents",label:x.name,detail:x.category,to:"/configuration"})),
  ...conversations.filter(x=>x.client.toLowerCase().includes(q)).slice(0,3).map(x=>({type:"Conversations",label:x.client,detail:x.message,to:"/service-client"})),
 ]},[query]);
 return <TooltipProvider><div className="min-h-screen bg-background">
  <aside className={`fixed inset-y-0 left-0 z-40 flex flex-col bg-sidebar text-sidebar-foreground transition-all duration-300 ${collapsed?"w-[76px]":"w-[258px]"} ${mobile?"translate-x-0":"-translate-x-full lg:translate-x-0"}`}>
   <div className="flex h-[72px] items-center gap-3 border-b border-sidebar-border px-5"><div className="grid size-9 shrink-0 place-items-center rounded-md bg-ai font-bold text-ai-foreground">LG</div>{!collapsed&&<div className="min-w-0"><p className="text-[13px] font-extrabold leading-tight text-sidebar-accent-foreground">LA GLOBALE</p><p className="text-[10px] font-semibold tracking-[.18em] text-sidebar-foreground/65">MAROCAINE</p></div>}<Button variant="ghost" size="icon" className="ml-auto hidden text-sidebar-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground lg:inline-flex" onClick={()=>setCollapsed(!collapsed)}>{collapsed?<PanelLeftOpen/>:<PanelLeftClose/>}</Button><Button variant="ghost" size="icon" className="ml-auto text-sidebar-foreground lg:hidden" onClick={()=>setMobile(false)}><X/></Button></div>
   <div className="mx-3 mt-4 rounded-md border border-ai/25 bg-ai/10 p-3">{collapsed?<Sparkles className="mx-auto size-5 text-ai"/>:<><div className="flex items-center gap-2 text-xs font-bold text-ai"><Sparkles className="size-4"/>4 AGENTS ACTIFS</div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-sidebar-border"><div className="h-full w-[68%] bg-ai"/></div><p className="mt-2 text-[10px] text-sidebar-foreground/65">Automatisation globale · 68%</p></>}</div>
   <nav className="mt-3 flex-1 space-y-1 overflow-y-auto px-3">{nav.map(([to,label,Icon])=><Tooltip key={to}><TooltipTrigger asChild><Link to={to} onClick={()=>setMobile(false)} className={`flex h-10 items-center gap-3 rounded-md px-3 text-[13px] font-medium transition ${path===to?"bg-sidebar-accent text-sidebar-accent-foreground shadow-sm":"text-sidebar-foreground/72 hover:bg-sidebar-accent/70 hover:text-sidebar-accent-foreground"}`}><Icon className={`size-[18px] shrink-0 ${path===to?"text-ai":""}`}/>{!collapsed&&<span className="truncate">{label}</span>}{label==="Notifications"&&!collapsed&&<span className="ml-auto rounded-full bg-warning px-1.5 text-[10px] font-bold text-primary-foreground">7</span>}</Link></TooltipTrigger>{collapsed&&<TooltipContent side="right">{label}</TooltipContent>}</Tooltip>)}</nav>
   <div className="border-t border-sidebar-border p-3"><div className={`flex items-center gap-3 rounded-md p-2 ${collapsed?"justify-center":""}`}><div className="grid size-9 shrink-0 place-items-center rounded-full bg-primary text-xs font-bold text-primary-foreground">AD</div>{!collapsed&&<div className="min-w-0 flex-1"><p className="text-xs font-bold text-sidebar-accent-foreground">Admin</p><p className="text-[10px] text-sidebar-foreground/55">Administrateur</p></div>}{!collapsed&&<Button variant="ghost" size="icon" className="size-8 text-sidebar-foreground" onClick={()=>navigate({to:"/"})}><LogOut className="size-4"/></Button>}</div></div>
  </aside>
  {mobile&&<div className="fixed inset-0 z-30 bg-foreground/30 lg:hidden" onClick={()=>setMobile(false)}/>} 
  <div className={`transition-all duration-300 ${collapsed?"lg:pl-[76px]":"lg:pl-[258px]"}`}>
   <header className="sticky top-0 z-20 flex h-[72px] items-center gap-3 border-b bg-card/95 px-4 backdrop-blur md:px-7"><Button variant="outline" size="icon" className="lg:hidden" onClick={()=>setMobile(true)}><Menu/></Button><div className="hidden items-center gap-2 text-xs text-muted-foreground sm:flex"><span>Plateforme IA</span><ChevronRight className="size-3"/><span className="font-semibold text-foreground">{title}</span></div><button onClick={()=>setSearchOpen(true)} className="ml-auto flex h-10 w-full max-w-md items-center gap-2 rounded-md border bg-panel px-3 text-left text-sm text-muted-foreground transition hover:border-primary/40"><Search className="size-4"/><span className="truncate">Rechercher clients, commandes, matières...</span><kbd className="ml-auto hidden rounded border bg-muted px-1.5 py-0.5 text-[10px] md:inline">⌘ K</kbd></button><Button variant="outline" size="icon" className="relative" onClick={()=>navigate({to:"/notifications"})}><Bell className="size-4"/><span className="absolute right-1 top-1 size-2 rounded-full bg-warning"/></Button><Button variant="outline" className="hidden gap-2 text-ai md:flex" onClick={()=>navigate({to:"/service-client"})}><Sparkles className="size-4"/>Assistant IA</Button></header>
   <main className="min-h-[calc(100vh-72px)] p-4 md:p-7"><div className="mx-auto max-w-[1600px] page-enter"><div className="mb-6"><h1 className="text-2xl font-extrabold tracking-normal md:text-[28px]">{title}</h1>{subtitle&&<p className="mt-1 text-sm text-muted-foreground">{subtitle}</p>}</div>{children}<footer className="mt-10 border-t py-5 text-center text-xs font-semibold text-muted-foreground">mvp created by izemx</footer></div></main>
  </div>
  <Dialog open={searchOpen} onOpenChange={setSearchOpen}><DialogContent className="top-[12%] max-w-2xl translate-y-0"><DialogHeader><DialogTitle>Recherche globale</DialogTitle></DialogHeader><Input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher dans toute la plateforme..." className="h-12"/><div className="max-h-[420px] overflow-auto">{query.length<2?<div className="py-12 text-center text-sm text-muted-foreground">Saisissez au moins 2 caractères</div>:results.length===0?<div className="py-12 text-center text-sm text-muted-foreground">Aucun résultat pour « {query} »</div>:<div className="space-y-1">{results.map((r,i)=><button key={i} onClick={()=>{setSearchOpen(false);navigate({to:r.to})}} className="flex w-full items-center gap-3 rounded-md p-3 text-left hover:bg-muted"><span className="w-24 text-[10px] font-bold uppercase text-ai">{r.type}</span><div className="min-w-0"><p className="text-sm font-semibold">{r.label}</p><p className="truncate text-xs text-muted-foreground">{r.detail}</p></div><ChevronRight className="ml-auto size-4 text-muted-foreground"/></button>)}</div>}</div></DialogContent></Dialog>
 </div></TooltipProvider>
}

export function PageHead({title,desc}:{title:string;desc:string}) { return null; }
