import { useMemo, useState, type ReactNode } from "react";
import { ArrowDown, ArrowUp, ArrowUpDown, ChevronLeft, ChevronRight, MoreHorizontal, RotateCcw, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";

export type DataColumn<T> = { key: string; label: string; value: (row:T)=>string|number; render?: (row:T)=>ReactNode; className?:string };
export type DataFilter<T> = { key:string; label:string; options:string[]; value:(row:T)=>string };

export function DataTable<T>({data,columns,filters=[],searchPlaceholder="Rechercher...",searchText=(r)=>JSON.stringify(r),pageSize=10,onView,onEdit,onDelete,onDuplicate}:{data:T[];columns:DataColumn<T>[];filters?:DataFilter<T>[];searchPlaceholder?:string;searchText?:(row:T)=>string;pageSize?:number;onView?:(row:T)=>void;onEdit?:(row:T)=>void;onDelete?:(row:T)=>void;onDuplicate?:(row:T)=>void}) {
 const [q,setQ]=useState(""); const [sort,setSort]=useState<{key:string;dir:"asc"|"desc"}|null>(null); const [selected,setSelected]=useState<Record<string,string>>({}); const [page,setPage]=useState(1);
 const rows=useMemo(()=>{let out=data.filter(r=>searchText(r).toLowerCase().includes(q.toLowerCase())&&filters.every(f=>!selected[f.key]||f.value(r)===selected[f.key]));if(sort){const col=columns.find(c=>c.key===sort.key);if(col)out=[...out].sort((a,b)=>{const av=col.value(a),bv=col.value(b);return (typeof av==="number"&&typeof bv==="number"?av-bv:String(av).localeCompare(String(bv),"fr",{numeric:true}))*(sort.dir==="asc"?1:-1)})}return out},[data,q,sort,selected,columns,filters,searchText]);
 const pages=Math.max(1,Math.ceil(rows.length/pageSize)); const visible=rows.slice((Math.min(page,pages)-1)*pageSize,Math.min(page,pages)*pageSize); const hasActions=onView||onEdit||onDelete||onDuplicate;
 const toggle=(key:string)=>{setPage(1);setSort(s=>!s||s.key!==key?{key,dir:"asc"}:s.dir==="asc"?{key,dir:"desc"}:null)};
 return <div><div className="mb-4 flex flex-wrap items-center gap-2"><div className="relative min-w-52 flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} className="pl-9" placeholder={searchPlaceholder}/></div>{filters.map(f=><select key={f.key} value={selected[f.key]??""} onChange={e=>{setSelected(v=>({...v,[f.key]:e.target.value}));setPage(1)}} className="h-9 rounded-md border bg-background px-3 text-xs"><option value="">{f.label}</option>{f.options.map(o=><option key={o}>{o}</option>)}</select>)}{(q||Object.values(selected).some(Boolean))&&<Button size="sm" variant="ghost" onClick={()=>{setQ("");setSelected({});setPage(1)}}><RotateCcw/>Réinitialiser les filtres</Button>}</div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b bg-muted/55 text-[10px] uppercase text-muted-foreground">{columns.map(c=><th key={c.key} className={`px-3 py-3 ${c.className??""}`}><button onClick={()=>toggle(c.key)} className="inline-flex items-center gap-1 font-bold hover:text-foreground">{c.label}{sort?.key===c.key?(sort.dir==="asc"?<ArrowUp className="size-3"/>:<ArrowDown className="size-3"/>):<ArrowUpDown className="size-3 opacity-45"/>}</button></th>)}{hasActions&&<th className="w-12 px-3 py-3">Actions</th>}</tr></thead><tbody>{visible.map((r,i)=><tr key={i} onClick={()=>onView?.(r)} className={`border-b transition hover:bg-accent/35 ${onView?"cursor-pointer":""}`}>{columns.map(c=><td key={c.key} className={`px-3 py-3 ${c.className??""}`}>{c.render?c.render(r):c.value(r)}</td>)}{hasActions&&<td className="px-3 py-2" onClick={e=>e.stopPropagation()}><DropdownMenu><DropdownMenuTrigger asChild><Button size="icon" variant="ghost"><MoreHorizontal/></Button></DropdownMenuTrigger><DropdownMenuContent align="end">{onView&&<DropdownMenuItem onClick={()=>onView(r)}>Voir</DropdownMenuItem>}{onEdit&&<DropdownMenuItem onClick={()=>onEdit(r)}>Modifier</DropdownMenuItem>}{onDuplicate&&<DropdownMenuItem onClick={()=>onDuplicate(r)}>Dupliquer</DropdownMenuItem>}{onDelete&&<DropdownMenuItem className="text-destructive" onClick={()=>onDelete(r)}>Supprimer</DropdownMenuItem>}</DropdownMenuContent></DropdownMenu></td>}</tr>)}</tbody></table>{visible.length===0&&<div className="py-14 text-center text-sm text-muted-foreground">Aucun résultat avec ces filtres.</div>}</div><div className="mt-4 flex items-center justify-between border-t pt-3 text-xs text-muted-foreground"><span>{rows.length} résultat{rows.length>1?"s":""}</span><div className="flex items-center gap-2"><span>Page {Math.min(page,pages)} / {pages}</span><Button size="icon" variant="outline" disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft/></Button><Button size="icon" variant="outline" disabled={page>=pages} onClick={()=>setPage(p=>p+1)}><ChevronRight/></Button></div></div></div>
}