import type { ReactNode } from "react";
import { TrendingUp, TrendingDown, Sparkles, Inbox } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export function StatusBadge({children,tone="neutral"}:{children:ReactNode;tone?:"success"|"warning"|"danger"|"info"|"neutral"|"ai"}) { const c={success:"bg-success-soft text-success",warning:"bg-warning-soft text-warning",danger:"bg-danger-soft text-destructive",info:"bg-secondary text-primary",neutral:"bg-muted text-muted-foreground",ai:"bg-accent text-ai"}[tone]; return <span className={`inline-flex items-center whitespace-nowrap rounded-full px-2 py-1 text-[10px] font-bold ${c}`}>{children}</span> }
export function KPI({label,value,change,icon:Icon,tone="primary"}:{label:string;value:string;change:number;icon:any;tone?:string}) { return <Card className="group overflow-hidden border bg-card shadow-none transition hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-md"><CardContent className="p-4"><div className="flex items-start justify-between"><div className={`grid size-9 place-items-center rounded-md ${tone==="ai"?"bg-accent text-ai":tone==="warning"?"bg-warning-soft text-warning":"bg-secondary text-primary"}`}><Icon className="size-[18px]"/></div><span className={`flex items-center gap-1 text-[11px] font-bold ${change>=0?"text-success":"text-destructive"}`}>{change>=0?<TrendingUp className="size-3"/>:<TrendingDown className="size-3"/>}{Math.abs(change)}%</span></div><p className="mt-4 text-2xl font-extrabold">{value}</p><p className="mt-1 text-[11px] font-medium text-muted-foreground">{label}</p><div className="mt-3 flex h-5 items-end gap-1">{[35,55,42,68,58,82,74,90].map((h,i)=><span key={i} className="flex-1 rounded-sm bg-primary/10 transition group-hover:bg-primary/25" style={{height:`${h}%`}}/>)}</div></CardContent></Card> }
export function SectionCard({title,action,children,className=""}:{title:string;action?:ReactNode;children:ReactNode;className?:string}) { return <Card className={`shadow-none ${className}`}><CardHeader className="flex-row items-center justify-between space-y-0 border-b px-5 py-4"><CardTitle className="text-sm font-extrabold">{title}</CardTitle>{action}</CardHeader><CardContent className="p-5">{children}</CardContent></Card> }
export function AiPanel({children,title="Analyse IA"}:{children:ReactNode;title?:string}) { return <div className="rounded-md border border-ai/25 bg-accent/45 p-4"><div className="mb-2 flex items-center gap-2 text-xs font-extrabold text-ai"><Sparkles className="size-4"/>{title}</div><div className="text-sm leading-6 text-foreground">{children}</div></div> }
export function EmptyState({label="Aucune donnée disponible"}:{label?:string}) { return <div className="grid min-h-48 place-items-center text-center"><div><Inbox className="mx-auto mb-3 size-8 text-muted-foreground/50"/><p className="text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-muted-foreground">Modifiez vos filtres ou ajoutez un nouvel élément.</p></div></div> }
export function Meta({title,description}:{title:string;description:string}) { return null; }
export const head=(title:string,description:string)=>({meta:[{title:`${title} — La Globale Marocaine`},{name:"description",content:description},{property:"og:title",content:`${title} — La Globale Marocaine`},{property:"og:description",content:description},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]});
