import type { ReactNode } from "react";
import { TrendingUp, TrendingDown, Sparkles, Inbox } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, ResponsiveContainer } from "recharts";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export function StatusBadge({children,tone="neutral"}:{children:ReactNode;tone?:"success"|"warning"|"danger"|"info"|"neutral"|"ai"}) { const c={success:"bg-success-soft text-success",warning:"bg-warning-soft text-warning",danger:"bg-danger-soft text-destructive",info:"bg-secondary text-primary",neutral:"bg-muted text-muted-foreground",ai:"bg-accent text-ai"}[tone]; return <span className={`inline-flex items-center whitespace-nowrap rounded-full px-2 py-1 text-[10px] font-bold ${c}`}>{children}</span> }
export function KPI({label,value,change,icon:Icon,tone="primary",data=[42,46,44,51,57,55,62,68],chart="area"}:{label:string;value:string;change:number;icon:any;tone?:string;data?:number[];chart?:"area"|"bar"}) { const points=data.map((v,i)=>({i,v})); return <Card className="group overflow-hidden border bg-card shadow-sm transition duration-200 hover:-translate-y-0.5 hover:border-primary/35 hover:shadow-md"><CardContent className="p-4 pb-2"><div className="flex items-start justify-between"><div className={`grid size-9 place-items-center rounded-md ${tone==="warning"?"bg-warning-soft text-warning":"bg-secondary text-primary"}`}><Icon className="size-[18px]"/></div><span className={`flex items-center gap-1 text-[11px] font-bold ${change>=0?"text-success":"text-destructive"}`}>{change>=0?<TrendingUp className="size-3"/>:<TrendingDown className="size-3"/>}{change>=0?"+":"−"}{Math.abs(change)}%</span></div><p className="mt-3 text-2xl font-extrabold">{value}</p><p className="mt-0.5 text-[11px] font-medium text-muted-foreground">{label}</p><div className="mt-2 h-10 w-full"><ResponsiveContainer width="100%" height="100%">{chart==="bar"?<BarChart data={points}><Bar dataKey="v" fill="var(--chart-2)" radius={[2,2,0,0]}/></BarChart>:<AreaChart data={points}><defs><linearGradient id={`kpi-${label.replaceAll(" ","")}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--chart-2)" stopOpacity={.28}/><stop offset="1" stopColor="var(--chart-2)" stopOpacity={0}/></linearGradient></defs><Area type="monotone" dataKey="v" stroke="var(--chart-1)" strokeWidth={2} fill={`url(#kpi-${label.replaceAll(" ","")})`} isAnimationActive={false}/></AreaChart>}</ResponsiveContainer></div></CardContent></Card> }
export function SectionCard({title,action,children,className=""}:{title:string;action?:ReactNode;children:ReactNode;className?:string}) { return <Card className={`shadow-none ${className}`}><CardHeader className="flex-row items-center justify-between space-y-0 border-b px-5 py-4"><CardTitle className="text-sm font-extrabold">{title}</CardTitle>{action}</CardHeader><CardContent className="p-5">{children}</CardContent></Card> }
export function AiPanel({children,title="Analyse IA"}:{children:ReactNode;title?:string}) { return <div className="rounded-md border border-ai/25 bg-accent/45 p-4"><div className="mb-2 flex items-center gap-2 text-xs font-extrabold text-ai"><Sparkles className="size-4"/>{title}</div><div className="text-sm leading-6 text-foreground">{children}</div></div> }
export function EmptyState({label="Aucune donnée disponible"}:{label?:string}) { return <div className="grid min-h-48 place-items-center text-center"><div><Inbox className="mx-auto mb-3 size-8 text-muted-foreground/50"/><p className="text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-muted-foreground">Modifiez vos filtres ou ajoutez un nouvel élément.</p></div></div> }
export function Meta({title,description}:{title:string;description:string}) { return null; }
export const head=(title:string,description:string)=>({meta:[{title:`${title} — La Globale Marocaine`},{name:"description",content:description},{property:"og:title",content:`${title} — La Globale Marocaine`},{property:"og:description",content:description},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]});
