/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchatsRouteImport } from './routes/achats'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DevisCommandesRouteImport } from './routes/devis-commandes'
import { Route as ServiceClientRouteImport } from './routes/service-client'
import { Route as StockRouteImport } from './routes/stock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchatsRoute = AchatsRouteImport.update({
  id: '/achats',
  path: '/achats',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisCommandesRoute = DevisCommandesRouteImport.update({
  id: '/devis-commandes',
  path: '/devis-commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceClientRoute = ServiceClientRouteImport.update({
  id: '/service-client',
  path: '/service-client',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achats': typeof AchatsRoute
  '/dashboard': typeof DashboardRoute
  '/devis-commandes': typeof DevisCommandesRoute
  '/service-client': typeof ServiceClientRoute
  '/stock': typeof StockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achats': typeof AchatsRoute
  '/dashboard': typeof DashboardRoute
  '/devis-commandes': typeof DevisCommandesRoute
  '/service-client': typeof ServiceClientRoute
  '/stock': typeof StockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achats': typeof AchatsRoute
  '/dashboard': typeof DashboardRoute
  '/devis-commandes': typeof DevisCommandesRoute
  '/service-client': typeof ServiceClientRoute
  '/stock': typeof StockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achats'
    | '/dashboard'
    | '/devis-commandes'
    | '/service-client'
    | '/stock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achats'
    | '/dashboard'
    | '/devis-commandes'
    | '/service-client'
    | '/stock'
  id:
    | '__root__'
    | '/'
    | '/achats'
    | '/dashboard'
    | '/devis-commandes'
    | '/service-client'
    | '/stock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchatsRoute: typeof AchatsRoute
  DashboardRoute: typeof DashboardRoute
  DevisCommandesRoute: typeof DevisCommandesRoute
  ServiceClientRoute: typeof ServiceClientRoute
  StockRoute: typeof StockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achats': {
      id: '/achats'
      path: '/achats'
      fullPath: '/achats'
      preLoaderRoute: typeof AchatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis-commandes': {
      id: '/devis-commandes'
      path: '/devis-commandes'
      fullPath: '/devis-commandes'
      preLoaderRoute: typeof DevisCommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-client': {
      id: '/service-client'
      path: '/service-client'
      fullPath: '/service-client'
      preLoaderRoute: typeof ServiceClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchatsRoute: AchatsRoute,
  DashboardRoute: DashboardRoute,
  DevisCommandesRoute: DevisCommandesRoute,
  ServiceClientRoute: ServiceClientRoute,
  StockRoute: StockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
